### ISSUE TITLE
无语了

### ISSUE THREAD

**Issue by FlorenceZh** [ThanatosXingYu/SchoolFool#1]
大哥您会写while循环吗.......
![image](https://user-images.githubusercontent.com/78526012/179723717-77f5629c-6698-43c7-82fc-a3401e8b7c1a.png) 
你写while 0==0： 我都能理解（方便调试），但是您那个变量 a 是干啥的。。。。

**Comment by ThanatosXingYu** [comment]
忘了删了
![%UVJ@W2{GZ1`@K~%{ZJ9FE4](https://user-images.githubusercontent.com/53430376/197440029-ce85c2c7-c591-40e3-a1e0-7695f3c06a17.png)
